#!/usr/bin/perl

use strict;
use File::Spec;
use File::Basename;

##############################################################################
##  get directory structure and include libraries
$::gCmd     = File::Spec->rel2abs($0);
$::gCmdDir  = dirname($::gCmd);
$::gCmdName = basename($::gCmd);
($::gCmdName, undef) = split(/\./, $::gCmdName);
$::gIncludeDir = File::Spec->catfile($::gCmdDir,'include');

# BC7708 V4.1 20-Dec-2006
# added block to use lib common library files first
if ( $^O =~ m/^vms$/i) {
  $::gLibCommon = File::Spec->catdir($ENV{'ATG_COMMON'},'libperl');
  $::gSQLCommon = File::Spec->catdir($ENV{'ATG_COMMON'},'libsql');
} elsif ( $^O =~ m/^(aix|hpux|linux)$/i ) {
$::gLibCommon = File::Spec->catdir($::gCmdDir,'common','libperl');
$::gSQLCommon = File::Spec->catdir($::gCmdDir,'common','libsql');
} else {
  # Call raiseErr -> dies with debugging info
  raiseErr(" \"RMAN not supported on $^O\" at ".__FILE__." line ".__LINE__."\n");
}
opendir(I,"$::gLibCommon") || die "Cannot add atg core libraries $::gLibCommon: $!\n";
my(@include) = readdir(I);
close(I);
for (@include){
require File::Spec->catfile($::gLibCommon,$_) if (m/\.ph$/);
}

if (! defined $ENV{'ORACLE_SID'}){
  print "Error ORACLE_SID must be set.";
}
if (! defined $ENV{'ORACLE_HOME'}){
  print "Error ORACLE_HOME must be set.";
}

my(%planHash);
my(@rval) = runSQL("$::gCmdDir/sql/pack_baselines.sql");
for (@rval){
  print $_;
  chomp;
  my($k,$v) = split /=>/,$_;
  $planHash{$k}=$v;
}

if ($planHash{'BASELINES_LOADED'} < 1){
  print "No accepted plans to export\n";
  exit;
}

if (-f "$::gCmdDir/query/$planHash{'TABLE_OWNER'}.$planHash{'TABLE_NAME'}.dmp"){
  print "\nWarning: Dumpfile exists!\nRemoving previous dumpfile\n";
  system("rm $::gCmdDir/query/$planHash{'TABLE_OWNER'}.$planHash{'TABLE_NAME'}.dmp");
}

my($cmd) = '$ORACLE_HOME/bin/expdp \"/ as sysdba\" ' .
          "directory=DM_PERF_DIR " .
          "tables=$planHash{'TABLE_OWNER'}.$planHash{'TABLE_NAME'} " .
          "dumpfile=$planHash{'TABLE_OWNER'}.$planHash{'TABLE_NAME'}.dmp " .
          "logfile=$planHash{'TABLE_OWNER'}.$planHash{'TABLE_NAME'}_EXPDP.log";
# print "$cmd\n";
system("$cmd");
exit;
